export const STORAGE_KEYS = {
  APP_INFO: "4567890234216778978023427895",
};

export const APP_TYPES = {
  UPDATE_USER: "@@APP/UPDATE_USER",
  UPDATE_LAYOUT: "@@APP/UPDATE_LAYOUT",
  UPDATE_ACCESS_LIMIT: "@@APP/UPDATE_ACCESS_LIMIT",
  RESET: "@@APP/RESET",
  REFRESH: "@@APP/REFRESH",
};

export const LOGIN_TYLES = {
  REQUEST: "@@LOGIN/LOGIN_REQUEST",
  SUCCESS: "@@LOGIN/LOGIN_SUCCESS",
  FAILED: "@@LOGIN/LOGIN_FAILED",
  RESET: "@@LOGIN/RESET",
  CHANGE: "@@LOGIN/CHANGE",
};


